Favlist
WildCodeSchool/2022-09-JS-Lille-project-3-g2-externatic pull request #30
Opened 2023-01-31 09:33 UTC by SOA-P

2023-01-31 09:44 UTC, hswiergiel submitted a review, later dismissed

2023-02-02 15:10 UTC, LoicBrassart requested changes
Stop disabling ESLint plz

2023-02-02 15:10 UTC, LoicBrassart commented on frontend/src/pages/Offer/Offer.jsx
> +/* eslint-disable import/no-extraneous-dependencies */
Remove this

2023-02-03 13:28 UTC, hswiergiel submitted a review, later dismissed

2023-02-03 14:24 UTC, LoicBrassart commented
Nope, the change I requested was not made

2023-02-03 14:24 UTC, LoicBrassart requested changes, later dismissed

2023-02-03 14:24 UTC, LoicBrassart commented on frontend/src/pages/Offer/Offer.jsx
> +/* eslint-disable import/no-extraneous-dependencies */
This code is still there

2023-02-06 08:40 UTC, Azahires approved these changes

2023-02-06 08:55 UTC, fantinerudent approved these changes

2023-02-08 08:39 UTC, merged