Sliderlastoffers
WildCodeSchool/2022-09-JS-Lille-project-3-g2-externatic pull request #4
Opened 2022-12-08 15:56 UTC by SOA-P

2022-12-08 16:12 UTC, Azahires approved these changes, later dismissed

2022-12-09 10:03 UTC, LoicBrassart commented
Missing first validation

2022-12-09 10:05 UTC, hswiergiel approved these changes, later dismissed

2022-12-09 10:15 UTC, LoicBrassart requested changes
Change CSS files to JSX with styled-components.
Otherwise, it seems fine to me

2022-12-09 16:14 UTC, hswiergiel approved these changes

2022-12-12 08:28 UTC, LoicBrassart approved these changes
SnE

2022-12-12 08:30 UTC, merged