Burgermenu
WildCodeSchool/2022-09-JS-Lille-project-3-g2-externatic pull request #5
Opened 2022-12-13 15:13 UTC by FlorianBartier

Added navigation bar with burger menu

2022-12-13 15:22 UTC, hswiergiel submitted a review, later dismissed

2022-12-14 08:24 UTC, LoicBrassart requested changes
Some Evils to fix
(@SM Plz read PR more carefully)

2022-12-14 08:24 UTC, LoicBrassart commented on frontend/src/components/BurgerMenu/BurgerMenu.jsx
> +                // navigate("/");
Dead code (repeat until end of file)

2022-12-14 08:24 UTC, LoicBrassart commented on frontend/src/components/BurgerMenu/style.jsx
> +  /* box-shadow: 0 1px 3px #c91961; */
Dead code

2022-12-14 08:24 UTC, LoicBrassart commented on package.json
> +  },
Nope

2022-12-14 10:04 UTC, FlorianBartier commented on frontend/src/components/BurgerMenu/BurgerMenu.jsx
> +                // navigate("/");
problem solved

2022-12-14 10:04 UTC, FlorianBartier commented on frontend/src/components/BurgerMenu/style.jsx
> +  /* box-shadow: 0 1px 3px #c91961; */
problem solved

2022-12-14 10:04 UTC, FlorianBartier commented on package.json
> +  },
problem solved

2022-12-14 10:05 UTC, hswiergiel approved these changes

2022-12-14 11:06 UTC, LoicBrassart approved these changes
Better!

2022-12-14 11:09 UTC, merged